"""Initial migration

Revision ID: 927577b68b2e
Revises: 
Create Date: 2025-05-08 03:09:51.160122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '927577b68b2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('english', sa.Text(), nullable=True),
    sa.Column('french', sa.Text(), nullable=True),
    sa.Column('pronunciation', sa.Text(), nullable=True),
    sa.Column('audio_file', sa.String(length=200), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word')
    op.drop_table('topic')
    # ### end Alembic commands ###
